site_name: Pearl - A Production-ready Reinforcement Learning AI Agent Library
theme: 
  name: material
  logo: assets/img/pearl.png
  palette:
    primary: custom
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
extra_css:
  - stylesheets/extra.css
nav:
  - Home:
    - index.md
  - Slides for Introduction:
    - pearl_detailed_intro.pdf
  - Documentation: 
    - documentation.html
  - Paper:
    - pearl_submission.pdf