# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Pearl - A Production-ready Reinforcement Learning AI Agent Library
email: billzhu@meta.com
description: | # this means to ignore newlines until "baseurl:"
  <p> Proudly brought by 
  <b>Applied Reinforcement Learning team, AI at Meta. </b> 
  </p>
  <img src="assets/img/team_logo.png">
  <p> Please find our paper at: xxx </p>
  <p> Cite us: </p> 
  <pre style="white-space: pre-wrap; word-break: keep-all;"><code>@misc{pearl2023paper,
  title = {Pearl - A Production-ready Reinforcement Learning AI Agent Library},

  author = {Zheqing Zhu, Rodrigo de Salvo Braz, Jalaj Bhandari, Daniel Jiang, Yi Wan, Yonathan Efroni, Ruiyang Xu, Liyuan Wang, Hongbo Guo, Alex Nikulkov, Dmytro Korenkevych, Urun Dogan, Frank Cheng, Zheng Wu, Wanqiao Xu},
  
  year = 2023,
  eprint = {arXiv:test}
  } 
  </code></pre>
baseurl: "" # the subpath of your site, e.g. /blog
url: "github.com/facebookresearch/pearl/" # the base hostname & protocol for your site, e.g. http://example.com
logo: "assets/img/pearl.jpg"

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

github:
  repository_url: "https://github.com/facebookresearch/pearl/"
  repository_nwo: "facebookresearch/pearl"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
